services:
  postgres:
    image: postgres:latest
    container_name: PostgreSQL-IoT-Weather-DB
    restart: always
    ports:
      - "8000:5432"
    environment:
      POSTGRES_PASSWORD: iot_admin
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin4:
    image: elestio/pgadmin:latest
    container_name: PGAdmin-Web-App
    restart: always
    ports:
      - "8001:8080"
    environment:
      PGADMIN_DEFAULT_EMAIL: iot_admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: iot_admin
      PGADMIN_LISTEN_PORT: 8080
volumes:
  pgdata:
